<html>
    <head>
        <script>
            function f0(){
                //var cu promisuri
                //var traditionala
                return new Promise((resolve, reject)=>{
                    let x
                    setTimeout(()=>{
                        x=100
                        resolve(x)
                    },1000)
                })
            }

            //modificare
            function f1(x){
                //var cu promisuri
                //var traditionala
                return new Promise((resolve, reject)=>{
                    let x
                    setTimeout(()=>{
                        x=100
                        resolve(x+100)
                    },2000)
                })
            }
            //modificare
            function f2(x){
                //var cu promisuri
                //var traditionala
                return new Promise((resolve, reject)=>{
                    let x
                    setTimeout(()=>{
                        x=100
                        resolve(x+200)
                    },3000)
                })
            }
            //similar exception mechanism
            //se face un chaining
            f0().then((result)=>{
                //console.log(result)
                return f1(result)
            }).then((result)=>{
                return f2(result)
            }).then((result)=>{
                console.log(result)
            }).catch((err)=>{
                console.log(err)
            })
        </script>
    </head>
</html>